Repository Azure/data-product-streaming, pull requests merged in 2021-11, with the labels that each got.

#77 Updated Codeowners
  .github/CODEOWNERS
Labels: enhancement, committed

#80 Updated Azure CLI Version
  .github/workflows/dataProductDeployment.yml
Labels: bug, committed

#82 updated param files for GitHub and ADO
  docs/EnterpriseScaleAnalytics-AzureDevOpsDeployment.md
  docs/EnterpriseScaleAnalytics-GitHubActionsDeployment.md
Labels: documentation

#83 Azure CLI Action Bugfix
  .github/workflows/dataProductDeployment.yml
Labels: bug, committed

#76 Make Cosmos DB, SQL Pool & Stream Analytics Deployment Optional
  docs/EnterpriseScaleAnalytics-AzureDevOpsDeployment.md
  docs/EnterpriseScaleAnalytics-GitHubActionsDeployment.md
  docs/EnterpriseScaleAnalytics-Prerequisites.md
  docs/reference/portal.dataProduct.json
  infra/main.bicep
  infra/main.json
  infra/modules/services/streamanalytics.bicep
  infra/modules/services/synapse.bicep
  infra/params.dev.json
  infra/params.prod.json
  infra/params.test.json
Labels: enhancement, committed

#79 Added Data Explorer Pool Deployment
  docs/EnterpriseScaleAnalytics-AzureDevOpsDeployment.md
  docs/EnterpriseScaleAnalytics-GitHubActionsDeployment.md
  docs/EnterpriseScaleAnalytics-Prerequisites.md
  docs/reference/portal.dataProduct.json
  infra/main.bicep
  infra/main.json
  infra/modules/services/synapse.bicep
  infra/params.dev.json
  infra/params.prod.json
  infra/params.test.json
Labels: feature, committed

#85 Updated Portal UI based on Feedback
  docs/reference/portal.dataProduct.json
Labels: feature, committed

#84 Fix Linting Issues
  .github/linters/.arm-ttk.psd1
  .github/workflows/lint.yml
  docs/EnterpriseScaleAnalytics-AzureDevOpsDeployment.md
  docs/EnterpriseScaleAnalytics-GitHubActionsDeployment.md
  docs/EnterpriseScaleAnalytics-Prerequisites.md
  infra/main.json
  infra/modules/services/eventhubnamespace.bicep
Labels: enhancement
